CREATE OR REPLACE TYPE TABLA_ANIDADA AS TABLE OF DIRECCION;
/
CREATE TABLE EJEMPLO_TABLA_ANIDADA(
    ID NUMBER(2),
    APELLIDO VARCHAR2(35),
    DIREC TABLA_ANIDADA)
    NESTED TABLE DIREC STORE AS DIREC_ANIDADA;

INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(1,'RAMOS',TABLA_ANIDADA(DIRECCION('CALLE MANANTIALES 2','GUADALAJARA', 19984),
    DIRECCION('CALLE MANANTIALES 2','GUADALAJARA', 19982),
    DIRECCION('CALLE MANANTIALES 3','GUADALAJARA', 19983),
    DIRECCION('CALLE MANANTIALES 4','GUADALAJARA', 19984),
    DIRECCION('CALLE MANANTIALES 5','GUADALAJARA', 19985))
);
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(2,'MARTIN',TABLA_ANIDADA(DIRECCION('CALLE HUESCA 2','ALCALÁ D EHENARES', 28008),
    DIRECCION('CALLE MANANTIALES 22','GUADALAJARA', 19982),
    DIRECCION('CALLE MANANTIALES 13','GUADALAJARA', 19983))
);

