CREATE OR REPLACE TYPE TIP_TELEFONOS IS VARRAY(3) OF VARCHAR(15);
/

CREATE OR REPLACE TYPE TIP_DIRECCION AS OBJECT(
    CALLE VARCHAR(50),
    POBLACION VARCHAR(50),
    CODPOST VARCHAR(20),
    PROVINCIA VARCHAR(40)
); 
/

CREATE OR REPLACE TYPE TIP_CLIENTE AS OBJECT(
    IDCLIENTE NUMBER,
    NOMBRE VARCHAR(50),
    DIREC TIP_DIRECCION,
    NIF VARCHAR(9),
    TELEF TIP_TELE FONOS
);
/

CREATE TYPE TABLA_CLIENTES AS TABLE OF TIP_CLIENTE;
/

CREATE OR REPLACE TYPE TIP_PRODUCTO AS OBJECT(
    IDPRODUCTO NUMBER,
    DESCRIPCION VARCHAR(80),
    PVP NUMBER,
    STOCKACTUAL NUMBER
);
/

CREATE OR REPLACE TYPE TIP_LINEA_VENTA AS OBJECT(
    NUMEROLINEA NUMBER,
    IDPRODUCTO REF TIP_PRODUCTO,
    CANTIDAD NUMBER
);
/

CREATE OR REPLACE TYPE TABLA_PRODUCTOS AS TABLE OF TIP_PRODUCTO;
/

CREATE OR REPLACE TYPE TAB_LINEA_VENTA AS TABLE OF TIP_LINEA_VENTA;
/

CREATE OR REPLACE TYPE TIP_VENTA AS OBJECT(
    IDVENTAS NUMBER,
    IDCLIENTE REF TIP_CLIENTE,
    FECHAVENTA DATE,
    LINEAS TAB_LINEA_VENTA,
    MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY TIP_VENTA 
    AS 
    MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER 
    IS
     i integer;
    tot number:=0;
    BEGIN
        for i in 1..LINEAS.count loop
          tot:=tot + (LINEAS(i).IDPRODUCTO.PVP * 
          LINEAS(i).CANTIDAD);
        end loop;
        return tot;
    END;
/