CREATE OR REPLACE TYPE TIP_TELEFONOS IS VARRAY(3) OF VARCHAR(15);
/

CREATE OR REPLACE TYPE TIP_DIRECCION AS OBJECT(
    CALLE VARCHAR(50),
    POBLACION VARCHAR(50),
    CODPOST VARCHAR(20),
    PROVINCIA VARCHAR(40)
); 
/

CREATE OR REPLACE TYPE TIP_CLIENTE AS OBJECT(
    IDCLIENTE NUMBER,
    NOMBRE VARCHAR(50),
    DIREC TIP_DIRECCION,
    NIF VARCHAR(9),
    TELEF TIP_TELEFONOS
);
/

CREATE OR REPLACE TYPE TIP_PRODUCTO AS OBJECT(
    IDPRODUCTO NUMBER,
    DESCRIPCION VARCHAR(80),
    PVP NUMBER,
    STOCKACTUAL NUMBER
);
/

CREATE OR REPLACE TYPE TIP_LINEA_VENTA AS OBJECT(
    NUMEROLINEA NUMBER,
    IDPRODUCTO REF TIP_PRODUCTO,
    CANTIDAD NUMBER
);
/

CREATE OR REPLACE TYPE TAB_LINEA_VENTA AS TABLE OF TIP_LINEA_VENTA;
/

CREATE OR REPLACE TYPE TIP_VENTA AS OBJECT(
    IDVENTAS NUMBER,
    IDCLIENTE REF TIP_CLIENTE,
    FECHAVENTA DATE,
    LINEAS TAB_LINEA_VENTA,
    MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY TIP_VENTA 
    AS 
    MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER 
    IS
     i integer;
    TOTAL number:=0;
    LINEA TIP_LINEA_VENTA;
    PRODUCT TIP_PRODUCTO;
    BEGIN
        for i in 1..LINEAS.count loop
            LINEA:=LINEAS(I);
            SELECT DEREF(LINEA.IDPRODUCTO) INTO PRODUCT FROM DUAL;
            TOTAL:=TOTAL+LINEA.CANTIDAD*PRODUCT.PVP;
        end loop;
        return TOTAL;
    END;
END;
/

DROP TABLE TABLA_CLIENTES;
CREATE TABLE TABLA_CLIENTES OF TIP_CLIENTE(IDCLIENTE PRIMARY KEY);

DROP TABLE TABLA_PRODUCTOS;
CREATE TABLE TABLA_PRODUCTOS OF TIP_PRODUCTO(IDPRODUCTO PRIMARY KEY);

DROP TABLE TABLA_VENTAS;
CREATE TABLE TABLA_VENTAS OF TIP_VENTA(IDVENTAS PRIMARY KEY)
NESTED TABLE LINEAS STORE AS TABLA_LINEAS;


INSERT INTO TABLA_CLIENTES VALUES(
    1,
    'Luis Garcia', 
    tip_direccion('calle Las Flores,23','Guadalajara','19003','Guadalajara'),
    '34343434L',
    tip_telefonos('949876655','949876655')
);
INSERT INTO TABLA_CLIENTES VALUES(
    2,
    'ana Serrano', 
    tip_direccion('calle Galiana 6','Guadalajara','19004','Guadalajara'),
    '76767667F',
    tip_telefonos('94980009')
);

INSERT INTO TABLA_PRODUCTOS VALUES(1, 'caja de cristal de murano',100,5);
INSERT INTO TABLA_PRODUCTOS VALUES(2, 'bicicleta city',120,15);
INSERT INTO TABLA_PRODUCTOS VALUES(3, '100 lapices de colores',20,5);
INSERT INTO TABLA_PRODUCTOS VALUES(4, 'ipad',600,5);
INSERT INTO TABLA_PRODUCTOS VALUES(5, 'ordenador portatil',400,10);

