CREATE OR REPLACE TYPE TELEFONO AS OBJECT(
    TIPO VARCHAR(30),
    NUMERO NUMBER
);
/

CREATE OR REPLACE TYPE LISTIN AS TABLE OF TELEFONO;
/

DROP TABLE CLIENTES3;
CREATE TABLE CLIENTES3(
    ID_CLI NUMBER,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    DIRECCION VARCHAR(30),
    POBLACION VARCHAR(30),
    PROVINCIA VARCHAR(30),
    TELEFONOS LISTIN)
    NESTED TABLE TELEFONOS STORE AS TEL_TAB
/

INSERT INTO STAFF VALUES(1,'FERNANDO','MORENO','CALLE MANANTIAL 50','MADRID','MADRID'TEL_TAB('MOVIL',626089187));
INSERT INTO STAFF VALUES(1,'FERNANDO','MORENO','CALLE MANANTIAL 50','MADRID','MADRID'TEL_TAB('MOVIL',626089187));/*NOSE AÑADIR 3 TELFS EN UN INSERT*/