DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    IDCLIENTE NUMBER,
    NOMBRE VARCHAR2(30),
    DIRECCION VARCHAR2(30),
    POBLACION VARCHAR2(30),
    CDPOSTAL VARCHAR(30),
    PROVINCIA VARCHAR2(30),
    NIF VARCHAR2(10),
    TEL1 NUMBER(9),
    TEL2 NUMBER(9),
    TEL3 NUMBER(9)
);

CREATE TABLE PRODUCTOS(
    IDPRODUCTO VARCHAR(), 
    DESCRIPCION
);