CREATE OR REPLACE TYPE TIP_DIREC AS OBJECT(
    DIR VARCHAR2(30),
    COD_POSTAL VARCHAR2(30)
);
/

CREATE OR REPLACE TYPE TIPO_CONTACTO AS OBJECT(
    TLF NUMBER,
    EMAIL VARCHAR2(30)
);
/

CREATE OR REPLACE TYPE TIPO_PERSONA AS OBJECT(
    ID NUMBER,
    NOMBRE VARCHAR2(30),
    APELLIDO VARCHAR2(30),
    DIREC TIP_DIREC,
    CONTACT TIPO_CONTACTO)
NOT FINAL
/

CREATE OR REPLACE TYPE TIP_CLIENT UNDER TIPO_PERSONA(
    N_PEDIDOS NUMBER
)
/

CREATE OR REPLACE TYPE TIPO_ART AS OBJECT(
    ID NUMBER,
    NOMBRE VARCHAR2(30),
    DESCRIPCION VARCHAR2(30),
    PRECIO NUMBER,
    PORCENTAJE NUMBER
);
/

CREATE OR REPLACE TYPE TAB_ARTICULO AS TABLE OF TIPO_ART;
/

CREATE OR REPLACE TYPE TIP_LDETALLE AS OBJECT(
    NUMERO NUMBER,
    ARTICLO TIPO_ART,
    CANTIDAD NUMBER
);
/

CREATE OR REPLACE TYPE TAB_DETALLE AS TABLE OF TIP_LDETALLE;
/

CREATE OR REPLACE TYPE TIP_LCOMPRA AS OBJECT(
    ID NUMBER,
    FECHA DATE,
    CLI REF TIP_CLIENT,
    DETALLE TAB_DETALLE,
    MEMBER FUNCTION TOTAL_LISTA RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY TIP_LCOMPRA 
IS
